apiVersion: v1
kind: Service
metadata:
  name: pedido-service
  namespace: pedido-namespace
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "HTTP"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "80"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/actuator/health/readiness"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "30"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-target-group-arn: ""arn:aws:elasticloadbalancing:us-east-1:643230847802:targetgroup/pedidos-fiap-burger-tg/71ebc311185c0819"
spec:
  selector:
    app: pedido-ms
  ports:
    - port: 80
      targetPort: 8989
  type: LoadBalancer
